apiVersion: apps/v1
kind: Deployment
metadata:
  name: decipher-deployment
spec:
  selector:
    matchLabels:
      app: decipher
  replicas: 3
  template:
    metadata:
      labels:
        app: decipher
    spec:
     containers:
     - name: decipher
       image: richard0323/decypher:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 8081
